#Análise de Dados – NumPy
***


***
**1.** Crie um array nulo de tamanho 10, mas com o 5° elemento valendo 1. 

In [ ]:
import numpy as np
array = np.zeros(10)
array[4] = 1
print('Array:\n', array)

Array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


***
**2.** Crie um array com valores inteiros variando entre 10 e 49 e inverta o array
(i.e., o 1o. elemento do array passa a ser o último). 

In [ ]:
import numpy as np
array = np.arange(10, 50)
reversed_arr = np.flip(array)
print('Array:\n\n', array)
print('\nReversed Array:\n\n ', reversed_arr)

Array:

 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reversed Array:

  [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]



***
**3.** Ache os índices não nulos do array [1, 2, 0, 0, 4, 0]. 

In [ ]:
import numpy as np

a = np.array([1, 2, 0, 0, 4, 0])
b = np.where(a>0)
indices = np.concatenate(b)
print(f'A = {a}')
print(f'Os índices dos elementos não nulos do vetor A são: {indices}')

A = [1 2 0 0 4 0]
Os índices dos elementos não nulos do vetor A são: [0 1 4]



***
**4.** Considere dois arrays de mesma dimensão. Confira se eles são iguais (usando só um
comando). 

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

comparacao = np.array_equal(a,b)

print(comparacao)

True


***
**5.** Execute o código em Python a seguir. Explique o resultado obtido.


In [ ]:
import numpy as np
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
a + b

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Para efetuar a soma das duas matrizes, o NumPy aumenta a dimensão de uma das matrizes (no caso a matriz 'b').

Posteriormente, o código apresenta o resultado dessa soma, na qual fica evidente que, para cada elemento presente em 'a', efetua-se a soma com b[0], b[1] e b[2], resultando nos três subconjuntos.

**Desse modo, temos:**

* [0 1 2] + [0] = [0 1 2]
* [0 1 2] + [1] = [1 2 3]
* [0 1 2] + [2] = [2 3 4]

###########

Ele soma o vetor A três vezes, uma vez em cada linha, então ele somou:

[0 1 2] + [0], [0 1 2] + [1] e [0 1 2] + [2]

Isso quer dizer que, se pegarmos a primeira soma, foram feitas as operações:

[[0]+[0], [0]+[1], [0]+[2]]

Resultando na saída:

[[0 1 2]

[1 2 3]

[2 3 4]]